var searchData=
[
  ['hookargs',['HookArgs',['../classOTA_1_1Plugin_1_1HookArgs.html',1,'OTA::Plugin']]],
  ['hookattribute',['HookAttribute',['../classOTA_1_1Plugin_1_1HookAttribute.html',1,'OTA::Plugin']]],
  ['hookcontext',['HookContext',['../structOTA_1_1Plugin_1_1HookContext.html',1,'OTA::Plugin']]],
  ['hookentry',['HookEntry',['../structOTA_1_1Plugin_1_1BasePlugin_1_1HookEntry.html',1,'OTA::Plugin::BasePlugin']]],
  ['hookpoint',['HookPoint',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'HookPoint'],['../classOTA_1_1Plugin_1_1HookPoint.html',1,'HookPoint&lt; T &gt;']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eaddban_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.AddBan &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2echestbreakreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ChestBreakReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2echestopenreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ChestOpenReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2ecommand_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.Command &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2econfigurationline_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ConfigurationLine &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2econnectionrequestreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ConnectionRequestReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2econsolemessagereceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ConsoleMessageReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2edeathmessage_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.DeathMessage &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2edisconnectreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.DisconnectReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2edoorstatechanged_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.DoorStateChanged &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2einvasionnpcspawn_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.InvasionNPCSpawn &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2einvasionwarning_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.InvasionWarning &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2einventoryitemreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.InventoryItemReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2ekillprojectilereceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.KillProjectileReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eliquidflowreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.LiquidFlowReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2enewconnection_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.NewConnection &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2enpchurt_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.NpcHurt &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2enpckilled_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.NPCKilled &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2enpcspawn_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.NPCSpawn &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eobituaryreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ObituaryReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eparsecommandlinearguments_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ParseCommandLineArguments &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2epartysettingreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PartySettingReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerauthenticationchanged_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerAuthenticationChanged &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerauthenticationchanging_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerAuthenticationChanging &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerchat_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerChat &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerdatareceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerDataReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerenteredgame_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerEnteredGame &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerenteringgame_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerEnteringGame &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerhurt_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerHurt &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerkilled_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerKilled &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerleftgame_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerLeftGame &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerpassreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerPassReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerpregreeting_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerPreGreeting &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayertriggeredevent_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerTriggeredEvent &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eplayerworldalteration_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PlayerWorldAlteration &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2epluginloadrequest_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PluginLoadRequest &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2epluginsloaded_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PluginsLoaded &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eprogramstart_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ProgramStart &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eprojectilereceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ProjectileReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2epvpsettingreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.PvpSettingReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2ereceivenetmessage_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ReceiveNetMessage &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2esendnetmessage_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.SendNetMessage &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eserverpassreceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ServerPassReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eserverstatechange_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.ServerStateChange &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2esigntextget_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.SignTextGet &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2esigntextset_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.SignTextSet &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2estartcommandprocessing_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.StartCommandProcessing &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2estartdefaultserver_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.StartDefaultServer &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2estateupdatereceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.StateUpdateReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2etilesquarereceived_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.TileSquareReceived &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoint_3c_20ota_3a_3aplugin_3a_3ahookargs_2eworldrequestmessage_20_3e',['HookPoint&lt; OTA::Plugin::HookArgs.WorldRequestMessage &gt;',['../classOTA_1_1Plugin_1_1HookPoint.html',1,'OTA::Plugin']]],
  ['hookpoints',['HookPoints',['../classOTA_1_1Plugin_1_1HookPoints.html',1,'OTA::Plugin']]]
];
